spring:
  config:
    import: classpath:/console.yaml,optional:file:${georchestra.datadir}/default.properties,optional:file:${georchestra.datadir}/console/console.yaml
  application:
    name: console
  datasource:
    url: jdbc:postgresql://${pgsqlHost}:${pgsqlPort}/${pgsqlDatabase}?currentSchema=console
    username: ${pgsqlUser}
    password: ${pgsqlPassword}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ldap:
    urls: ${ldapScheme}://${ldapHost}:${ldapPort}
    base: dc=georchestra,dc=org
    username: cn=admin,dc=georchestra,dc=org
    password: secret

server:
  servlet:
    context-path: /console
